env:
  es6: true
  node: false
  browser: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 2019
  sourceType: 'module'

rules:
  indent:
    - error
    - 2
  no-use-before-define: 0
  comma-dangle: 0
  no-param-reassign: 0
  no-plusplus: 0
  arrow-body-style: 0
  guard-for-in: 0
  no-restricted-syntax: 0
